### ISSUE TITLE
Change file system for pages

### ISSUE THREAD

**Issue by DakoMumladze** [task-er/tasker-monorepo#68]
Now in `src` folder we have `pages` folder, each page includes jsx with it's own styles.
We want to add folders for each component and they should have separately `index.js` and `style.js` files.
See the attached example below:
```markdown
* src
  * /pages
    * /login
      * index.js
      * style.js
    * /register
      * index.js
      * style.js
    * /reset-password
      * index.js
      * style.js
    * /forgot-password
      * index.js
      * style.js
```

**Comment by shavidzet** [comment]
> UI layer separated as jsx and style files. But we didn't achieve exact idea of this issue and the job has been done partly in https://github.com/task-er/tasker-monorepo/pull/72 and now the issues is awaiting to finish https://github.com/task-er/tasker-monorepo/pull/76
